// <auto-generated />
using System;
using COREMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace COREMVC.Data.Migrations
{
    [DbContext(typeof(DimeDataDBContext))]
    [Migration("20201108012855_InitialCommmit")]
    partial class InitialCommmit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("COREMVC.Models.DepartmentTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("id");

                    b.ToTable("Department_Table$");
                });

            modelBuilder.Entity("COREMVC.Models.EmployeesTable", b =>
                {
                    b.Property<double?>("EmployeeNumber")
                        .HasColumnType("float");

                    b.Property<double?>("Age")
                        .HasColumnType("float");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EducationField")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("EnvironmentSatisfaction")
                        .HasColumnType("float");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("HourlyRate")
                        .HasColumnType("float");

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("JobSatisfaction")
                        .HasColumnType("float");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("MonthlyIncome")
                        .HasColumnType("float");

                    b.Property<double?>("RelationshipSatisfaction")
                        .HasColumnType("float");

                    b.Property<double?>("StandardHours")
                        .HasColumnType("float");

                    b.Property<double?>("StockOptionLevel")
                        .HasColumnType("float");

                    b.HasKey("EmployeeNumber");

                    b.ToTable("Employees_Table$");
                });

            modelBuilder.Entity("COREMVC.Models.EmployeesTableExternalData1", b =>
                {
                    b.Property<double?>("EmployeeNumber")
                        .HasColumnType("float");

                    b.Property<double?>("Age")
                        .HasColumnType("float");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EducationField")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("EnvironmentSatisfaction")
                        .HasColumnType("float");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("HourlyRate")
                        .HasColumnType("float");

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("JobSatisfaction")
                        .HasColumnType("float");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("MonthlyIncome")
                        .HasColumnType("float");

                    b.Property<double?>("RelationshipSatisfaction")
                        .HasColumnType("float");

                    b.Property<double?>("StandardHours")
                        .HasColumnType("float");

                    b.Property<double?>("StockOptionLevel")
                        .HasColumnType("float");

                    b.HasKey("EmployeeNumber");

                    b.ToTable("Employees_Table$ExternalData_1");
                });

            modelBuilder.Entity("COREMVC.Models.HumanResourceTable", b =>
                {
                    b.Property<double?>("EmployeeNumber")
                        .HasColumnType("float");

                    b.Property<double?>("Age")
                        .HasColumnType("float");

                    b.Property<string>("BusinessTravel")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("DistanceFromHome")
                        .HasColumnType("float");

                    b.Property<string>("EducationField")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("NumCompaniesWorked")
                        .HasColumnType("float");

                    b.Property<string>("OverTime")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("TotalWorkingYears")
                        .HasColumnType("float");

                    b.Property<double?>("TrainingTimesLastYear")
                        .HasColumnType("float");

                    b.Property<double?>("YearsAtCompany")
                        .HasColumnType("float");

                    b.Property<double?>("YearsInCurrentRole")
                        .HasColumnType("float");

                    b.Property<double?>("YearsSinceLastPromotion")
                        .HasColumnType("float");

                    b.Property<double?>("YearsWithCurrManager")
                        .HasColumnType("float");

                    b.HasKey("EmployeeNumber");

                    b.ToTable("Human_Resource_Table$");
                });

            modelBuilder.Entity("COREMVC.Models.HumanResourceTableExternalData1", b =>
                {
                    b.Property<double?>("Age")
                        .HasColumnType("float");

                    b.Property<string>("BusinessTravel")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("DistanceFromHome")
                        .HasColumnType("float");

                    b.Property<string>("EducationField")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("EmployeeNumber")
                        .HasColumnType("float");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("NumCompaniesWorked")
                        .HasColumnType("float");

                    b.Property<string>("OverTime")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("TotalWorkingYears")
                        .HasColumnType("float");

                    b.Property<double?>("TrainingTimesLastYear")
                        .HasColumnType("float");

                    b.Property<double?>("YearsAtCompany")
                        .HasColumnType("float");

                    b.Property<double?>("YearsInCurrentRole")
                        .HasColumnType("float");

                    b.Property<double?>("YearsSinceLastPromotion")
                        .HasColumnType("float");

                    b.Property<double?>("YearsWithCurrManager")
                        .HasColumnType("float");

                    b.ToTable("Human_Resource_Table$ExternalData_1");
                });

            modelBuilder.Entity("COREMVC.Models.LoginTable", b =>
                {
                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.ToTable("Login_Table$");
                });

            modelBuilder.Entity("COREMVC.Models.ManagerTable", b =>
                {
                    b.Property<double?>("EmployeeNumber")
                        .HasColumnType("float");

                    b.Property<string>("Attrition")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("DailyRate")
                        .HasColumnType("float");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("EmployeeCount")
                        .HasColumnType("float");

                    b.Property<double?>("HourlyRate")
                        .HasColumnType("float");

                    b.Property<double?>("JobInvolvement")
                        .HasColumnType("float");

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("MonthlyIncome")
                        .HasColumnType("float");

                    b.Property<double?>("MonthlyRate")
                        .HasColumnType("float");

                    b.Property<string>("OverTime")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("PercentSalaryHike")
                        .HasColumnType("float");

                    b.Property<double?>("PerformanceRating")
                        .HasColumnType("float");

                    b.Property<double?>("StandardHours")
                        .HasColumnType("float");

                    b.HasKey("EmployeeNumber");

                    b.ToTable("Manager_Table$");
                });

            modelBuilder.Entity("COREMVC.Models.RegistrationTable", b =>
                {
                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EducatiionField")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.ToTable("Registration_Table$");
                });

            modelBuilder.Entity("COREMVC.Models.RolesTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobRoles")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("id");

                    b.ToTable("Roles_Table$");
                });
#pragma warning restore 612, 618
        }
    }
}
